Privatix/dappctrl

dappctrl-test.config.json
data/schema.go
data/schema.sql
main.go
vpn/mon/monitor.go
vpn/mon/monitor_test.go
vpn/srv/misc.go
vpn/srv/server_test.go
vpn/srv/start.go
vpn/util/misc.go
vpn/util/test.go

This change fully resolves **BV-92**.

Tests for OpenVPN monitor.

---

dappctrl-test.config.json
dappctrl.config.json
data/misc.go
data/schema.go
data/test.go
main.go
payment/hash.go
payment/middleware.go
payment/misc.go
payment/pay.go
payment/pay_test.go
payment/server.go
util/misc.go

Payment receiver server implemented as a distinct server on a separate `http.ServeMux`. Tests are agains real postgres db using `httptest`.

payment(balance proof) receiver server

---

.gitignore
Dockerfile
README.md
docker-compose.yaml
vpn.dockerfile

Images are hosted at https://hub.docker.com/u/privatix/dashboard/

vpn, dappctrl dockerfiles and docker-compose file

---

dappctrl-test.config.json
dappctrl.config.json
main.go
somc/conn.go
somc/conn_test.go
somc/find_offerrings.go
somc/misc.go
somc/publish_endpoint.go
somc/publish_offering.go
somc/wait_for_endpoint.go
vpn/srv/server.go

This change introduces a new *somc* package which contains means for:
1. Publishing service offerings.
2. Retrieving service offerings by given hashes.
3. Publishing service offering endpoints.
4. Getting endpoint for requested offering.
Resolves **BV-123**.

SOMC communication support.

---

README.md
eth/lib/common_test.go
eth/lib/logs_test.go
eth/lib/tests/utils.go
eth/lib/types_test.go
payment/pay_test.go
somc/conn_test.go
vpn/mon/monitor_test.go
vpn/srv/server_test.go

Ability to exclude specific tests from test run.

---

data/schema_0.6.sql

This version adds following objects: job queue, eth logs, eth transactions, endpoints messages.

DB scheme changes

---

.codeclimate.yml

Summary:
* removed cognitive complexity check
* removed return statement count check
* increased method lines count

add suggestions

---

dappctrl-test.config.json
dappctrl.config.json
data/schema.go
data/schema.sql
job/queue.go
job/queue_test.go
job_handler.go
main.go
util/test.go

This change contains:
1. Job-related DB schema improvements.
2. Job queue type which supports addition and processing.
3. Corresponding unit-tests.
Resolves BV-147, BV-149.

Job queue with parallel processing.

---

data/schema.sql

some constraints name are not unique. fixing.

fix db unique constraints names

---

README.md
data/db.go
svc/dappvpn/README.md
svc/dappvpn/dappvpn.config.json
tool/dappinst/main.go
util/misc.go

This change contains:
1. README.md for dappvpn configuration.
2. Installation tool which creates a new product in the database and updates a given dappvpn configuration.
Resolves BV-266.

Instruction and tool for OpenVPN adapter configuration.

---

data/schema.sql

Verify offering max units

---

tool/initializer/initializer.py

initializer create BV-224

---

monitor/schedule.go

Agent was missing create offering event scheduler

Added scheduleAgentOfferingCreated

---

data/prod_data.sql
tool/dappinst/main.go

dappinst set unique product id and random password.

---

dappctrl-test.config.json
dappctrl.prod.config.json
data/schema.go
main.go
proc/worker/agent.go
proc/worker/agent_test.go
proc/worker/common.go
proc/worker/common_test.go
proc/worker/misc.go
proc/worker/worker_test.go
tool/initializer/initializer.py
uisrv/account.go
uisrv/channel.go
uisrv/channel_test.go
uisrv/db.go
uisrv/misc.go
uisrv/offering.go
uisrv/offering_test.go
uisrv/server.go
uisrv/server_test.go

- Create UI back-end endpoints according to swagger specification.
- Implement REST endpoints handlers for Client UI
Resolves BV-296, BV-298.

Implement REST endpoints handlers for Client UI

---

proc/worker/adapter.go
proc/worker/misc.go

Add ETH balance check to `addCheckBalance` job

Add ETH balance check

---

dappctrl-test.config.json
data/misc.go
data/schema.go
data/schema.sql
data/test.go
main.go
messages/ept/config/client.go
proc/job_handler.go
proc/worker/adapter.go
proc/worker/adapter_test.go
proc/worker/agent_test.go
proc/worker/client.go
proc/worker/client_test.go
proc/worker/errors.go
proc/worker/misc.go
proc/worker/worker.go
proc/worker/worker_test.go
somc/fake_somc.go
statik/generate.go
statik/misc.go
util/validation.go

This change includes:
1. ClientPreChannelCreate implementation and test.
2. ClientAfterChannelCreate implementation and test.
3. ClientPreEndpointMsgSOMCGet implementation and test.
4. ClientAfterEndpointMsgSOMCGet implementation and test.
5. Miscellaneous utilities and refactoring bits.
Partially resolves BV-292.

Tasks for the client channel/endpoint setup flow.

---

dappctrl-test.config.json
dappctrl.config.json
data/schema.go
data/schema.sql
data/test.go
data/test_data.sql
main.go
messages/ept/config/client.go
messages/ept/config/client_test.go
messages/ept/config/errors.go
messages/ept/config/server_test.go
messages/ept/errors.go
messages/ept/misc.go
messages/ept/service.go
messages/ept/service_test.go
proc/worker/client.go
proc/worker/client_test.go
proc/worker/worker.go
proc/worker/worker_test.go

Simplify endpoint message deployment.

---

dappctrl-test.config.json
monitor/monitor_test.go
proc/job_handler.go
proc/worker/client.go
proc/worker/client_test.go

Add job ClientAfterUncooperativeClose.

---

monitor/monitor_test.go
proc/job_handler.go
proc/worker/client.go
proc/worker/client_test.go

 Add job ClientAfterCooperativeClose.

---

dappctrl-test.config.json
monitor/monitor_test.go
proc/job_handler.go
proc/worker/adapter.go
proc/worker/adapter_test.go
proc/worker/client.go
proc/worker/client_test.go
proc/worker/worker_test.go

Add job ClientPreUncooperativeClose.

---

data/prod_data.sql
data/schema.sql

* Added constraints to for unique values on: templates.hash, offerings.hash, accounts.eth_addr, users.eth_addr
* Changed names of templates
*  Added product: VPN client

sql minor changes

---

main.go
uisrv/channel.go
uisrv/channel_test.go
uisrv/server.go
uisrv/server_test.go

Enable `/client/channels/{id}/status` to change service status via `proc/channel`.
Resolves BV-397.

Enable UI API endpoints for client Suspend, Unsuspend, Terminate.

---

messages/ept/config/client.go
messages/ept/config/client_test.go
messages/ept/config/server.go
messages/ept/config/server_test.go
svc/dappvpn/main.go
svc/dappvpn/pusher/pusher.go
svc/dappvpn/pusher/pusher_test.go

DappVPN server pusher resolve external IP and push with OpenVPN config.

---

data/prod_data.sql

Add SQL INSERT statement for all settings except:
- system.password;
- system.salt;
to prod_data.sql.
Resolves BV-412.

Add all settings to prod_data.sql.

---

data/misc.go
data/schema.go
monitor/schedule.go

Separate job scheduling in blockchain monitor according to user role in settings.

---

monitor/schedule.go
proc/worker/client.go
proc/worker/client_test.go

Fix ClientAfterChannelCreate job.

---

dappctrl-test.config.json
dappctrl.config.json
dappctrl.prod.config.json
main.go
proc/processor/processor.go
svc/dappvpn/main.go
tool/dappinst/main.go
util/log.go

Add dappctr config option to write logs to file.

---

monitor/schedule.go

Add returnBalanceERC20 event to monitor event scheduler.

---

data/schema.sql
monitor/monitor_test.go
proc/worker/agent.go

Bugfixes for BV-428 and BV-443.

---

data/misc.go
monitor/schedule.go
proc/worker/agent.go
proc/worker/agent_test.go
proc/worker/client.go
proc/worker/client_test.go
proc/worker/misc.go
somc/fake_somc.go
somc/get_endpoint.go
somc/publish_endpoint.go
statik/templates/ept.json
uisrv/channel.go
uisrv/db.go
uisrv/offering.go
uisrv/offering_test.go

Fix ClientPreEndpointMsgSOMCGet, ClientAfterChannelCreate jobs

---

monitor/schedule.go
uisrv/channel.go
uisrv/channel_test.go

Fix client\channels endpoint returns duplicated channels.

---

dappctrl.config.json
dappctrl.prod.config.json
report/bugsnag/bugsnag.go

Manual Bugsnag release stage.

---

proc/worker/common.go
uisrv/account.go

Remove unnecessary job.ID && job.Status.

---

dappctrl.config.json
eth/client.go
main.go

Ethereum client request timeout.

---

tool/initializer/initializer.py

Add dnsmasq check and dev mode

initializer BV-224

---

messages/ept/config/client.go
statik/ovpn/templates/client-config.tpl

Change client.ovpn config template.

---

agent/bill/monitor.go
agent/bill/sec_test.go

time based billing is still not supported, so removing it to simplify code

Update agent billing to  use units based calculations

---

data/schema.go

Resolves BV-581.
Added fields for GET `/endpoints` endpoint response: paymentReceiverAddress, serviceEndpointAddress.

Added additional fields for get endpoints.

---

agent/bill/monitor.go
agent/bill/monitor_test.go
dappctrl-dev.config.json
dappctrl-test.config.json
dappctrl.config.json
main.go

 Interval between rounds of processing is added for a configuration.

---

data/prod_data.sql
data/schema.go
data/schema.sql
main.go
uisrv/auth.go
uisrv/db.go
uisrv/setting.go
uisrv/setting_test.go

Resolves BV-409, BV-658, BV-659.

Added permissions for settings.

---

uisrv/setting.go

Resolves BV-670.
Fixed PUT `/settings` endpoint  from uisrv.

Offer can be published.

---

main.go
messages/ept/errors.go
messages/ept/misc.go
messages/ept/service.go
messages/ept/service_test.go
proc/worker/worker.go
proc/worker/worker_test.go

Refactor logging for ept pkg.

---

eth/client.go
eth/errors.go

Refactor logging for eth pkg.

---

main.go
monitor/collect.go
monitor/errors.go
monitor/monitor.go
monitor/monitor_test.go
monitor/schedule.go

Refactor logging for monitor pkg.

---

svc/dappvpn/config/config.go
svc/dappvpn/dappvpn.config.json
svc/dappvpn/main.go
svc/dappvpn/msg/config.go
svc/dappvpn/msg/config_test.go
svc/dappvpn/msg/errors.go
svc/dappvpn/msg/msg_test.go
svc/dappvpn/msg/parsing.go
svc/dappvpn/msg/parsing_test.go
svc/dappvpn/msg/pusher.go
svc/dappvpn/msg/pusher_test.go
svc/dappvpn/prepare/errors.go
svc/dappvpn/prepare/prepare.go
svc/dappvpn/prepare/prepare_test.go

Refactor logging for prepare and msg pkgs.

---

main.go

Refactor logging for main pkg.

---

main.go
sesssrv/auth.go
sesssrv/client.go
sesssrv/endpoint_test.go
sesssrv/errors.go
sesssrv/misc.go
sesssrv/product.go
sesssrv/product_test.go
sesssrv/server.go
sesssrv/server_test.go
sesssrv/session_test.go
sesssrv/start.go
sesssrv/stop.go
svc/dappvpn/main.go
svc/dappvpn/msg/msg_test.go
svc/dappvpn/msg/pusher.go
svc/dappvpn/prepare/prepare.go
svc/dappvpn/prepare/prepare_test.go

Refactor logging for sesssrv pkg.

---

dappctrl.config.json
main.go
report/bugsnag/bugsnag.go
report/log/logger.go
report/reporter.go

Refactor logging and Bugsnag client

---

agent/bill/monitor_test.go
client/bill/monitor_test.go
client/svcrun/runner_test.go
job/errors.go
job/queue.go
job/queue_test.go
main.go
proc/channel_test.go
proc/worker/worker_test.go
uisrv/server_test.go

Refactor logging for job pkg.

---

main.go

Log to file as well.

---

eth/contract/abis/psc.abi
proc/worker/adapter.go
proc/worker/adapter_test.go
proc/worker/client.go
proc/worker/client_test.go

Replaced GetOfferingSupply() with GetOfferingInfo().

---

dappctrl-dev.config.json
dappctrl.config.json

Increase Ethereum client & block monitor schedule timeouts & changed GethURL

---

data/misc.go
proc/worker/client.go
proc/worker/client_test.go
proc/worker/errors.go

Refactor clientAfterOfferingMsgBCPublish.

---

uisrv/offering.go
uisrv/offering_test.go

Sorting offerings by block_number_updated for Agent in UI.

---

data/schema.go
monitor/schedule.go
monitor/schedule_test.go
proc/handlers/job.go
proc/worker/adapter.go
proc/worker/adapter_test.go
proc/worker/agent.go
proc/worker/agent_test.go
proc/worker/errors.go

 Refactor AgentPreOfferingPopUp & added AgentAfterOfferingPopUp

---

dappctrl-dev.config.json
dappctrl.config.json
main.go
report/bugsnag/bugsnag.go

Use application version for reports.

---

data/prod_data.sql

@ubozov 
Is this enough for the migration?
Do I need to fix this value elsewhere?

fix challenge_period

---

doc/ui/rpc.md
ui/db.go
ui/errors.go
ui/object.go
ui/template.go
ui/template_test.go

Move templates endpoints to a JSON RPC server.

---

client/bill/monitor.go
client/bill/monitor_test.go
pay/client.go
pay/misc.go
pay/pay.go
pay/pay_test.go

Agent notifies about channel termination.

---

doc/ui/rpc.md
ui/db.go
ui/errors.go
ui/misc.go
ui/settings.go
ui/settings_test.go

Move settings endpoints to a JSON RPC server.

---

doc/ui/rpc.md
main.go
ui/account.go
ui/account_test.go
ui/errors.go
ui/handler.go
ui/handler_test.go

Move accounts endpoints to a JSON RPC server.

---

doc/ui/rpc.md
ui/account.go
ui/account_test.go
ui/errors.go
ui/misc.go
ui/offering.go
ui/offering_test.go

Move offerings endpoints to a JSON RPC server.

---

dappctrl-dev.config.json
dappctrl.config.json
main.go
proc/worker/agent.go
proc/worker/agent_test.go
proc/worker/errors.go
proc/worker/misc.go
proc/worker/worker.go
proc/worker/worker_test.go

Fill offering country code.

---

dappctrl-dev.config.json
dappctrl.config.json

Change PSC address according: https://privatix.atlassian.net/wiki/spaces/BVD/pages/343572481/Dev+and+prod+configurations

change PSC address

---

client/bill/monitor.go
client/bill/monitor_test.go
client/svcrun/runner.go
client/svcrun/runner_test.go
dappctrl-test.config.json
main.go
monitor/collect_test.go
monitor/monitor.go
monitor/monitor_test.go
monitor/schedule_test.go

Fix tests with timeout.

---

svc/connector/connector.go
svc/connector/test.go

Change `Connector` interface to transfer `tc` package to `dapp-openvpn` repository.

Change `Connector` interface.

---

ui/misc.go

Fix account & offering creation.

---

job/queue.go
job/queue_test.go
job/test.go
monitor/monitor.go
monitor/monitor_test.go
monitor/schedule.go
proc/channel.go
proc/worker/agent.go
proc/worker/client.go
proc/worker/misc.go
ui/account.go
ui/account_test.go
ui/channel.go
ui/channel_test.go
ui/offering.go
ui/offering_test.go
ui/subscribe_test.go
uisrv/account.go
uisrv/channel.go
uisrv/offering.go

Support job addition within transactions

---

agent/bill/monitor_test.go
client/bill/monitor_test.go
client/svcrun/runner_test.go
dappctrl-dev.config.json
dappctrl-test.config.json
dappctrl.config.json
job/queue_test.go
main.go
messages/ept/service_test.go
monitor/monitor_test.go
pay/pay_test.go
proc/channel_test.go
proc/worker/worker_test.go
sesssrv/server_test.go
somc/conn_test.go
svc/dappvpn/dappvpn.config.json
svc/dappvpn/main.go
svc/dappvpn/mon/monitor_test.go
svc/dappvpn/msg/msg_test.go
svc/dappvpn/prepare/prepare_test.go
ui/handler_test.go
uisrv/server_test.go
util/log/file_logger.go

Support configurable path for file loggers

---

monitor/schedule.go
monitor/schedule_test.go

Fix a offering removed event.

---

messages/offer/offering.go
proc/worker/client.go
proc/worker/client_test.go
proc/worker/errors.go

Checks:
1. Check hash match to that in registered in blockchain.
2. Validate offering JSON compliant with offering template JSON.
Resolves BV-888.

Validate offering using template.

---

ui/auth.go
ui/auth_test.go
ui/handler_test.go

Re-encrypt private keys after password change.

---

doc/ui/rpc.md
ui/account.go
ui/account_test.go

Update account state.

---

report/bugsnag/bugsnag.go

Include the addresses of all accounts in the report to bugsnag.

---

statik/misc.go
statik/misc_linux.go
statik/misc_windows.go
statik/pkgList/gen.bat

Adapt inline go generate to build on windows

fix statik to build on windows

---

dappctrl-test.config.json
doc/ui/rpc.md
proc/looper/loop_test.go
proc/looper/offering_test.go
ui/income.go
ui/income_test.go
ui/misc.go

Add getTotalIncome method.

---

doc/ui/rpc.md
ui/eth_tx.go
ui/eth_tx_test.go

Add accountAggregated type to getEthTransactions method.

---

doc/ui/rpc.md
main.go
ui/auth_test.go
ui/channel.go
ui/channel_test.go
ui/db.go
ui/errors.go
ui/export_test.go
ui/handler.go
ui/handler_test.go
ui/misc.go
util/misc.go

Add channels methods.

---

doc/ui/rpc.md
ui/account.go
ui/channel.go
ui/misc.go
ui/object.go
ui/offering.go
ui/offering_test.go

Get offerings pagination.

---

doc/ui/rpc.md
ui/channel.go
ui/eth_tx.go
ui/eth_tx_test.go

Get Ethereum transactions pagination.

---

main.go

Catch panic to file logger.

---

ui/channel.go
ui/channel_test.go
ui/db.go
ui/errors.go

Fix GetClientChannels.

---

doc/ui/rpc.md
ui/channel.go
ui/channel_test.go

Add to getClientsChannels offering hash.

---

ui/logs.go

Log filter ignored severity, when using full text search.
Resolves BV-1004.

Fix log filter when using full text search.

---

doc/ui/rpc.md
ui/setting.go
ui/setting_test.go

GetSettings method returns settings permissions

---

doc/ui/rpc.md
ui/offering.go
ui/offering_test.go

Get offerings filter parameters for client.

---

doc/ui/rpc.md
ui/object.go
ui/object_test.go

Get an object from database by hash.

Get object by hash

---

client/bill/monitor.go
pay/client.go
pay/misc.go
pay/pay_test.go
proc/worker/agent_test.go

Add error `equalBalance` to pay server.

---

proc/worker/account.go
proc/worker/account_test.go

Service balance updated to client after top up channel.

---

doc/ui/rpc.md
ui/channel.go
ui/channel_test.go

Replace status strings to status arrays in a getAgentChannels method.

---

.gitignore
data/command.go
data/create_db.sql
tool/copy_dbscripts/copy.go

create db via dappctrl db-create command

---

agent/bill/monitor.go
client/bill/monitor.go
job/queue.go
proc/looper/loop.go
proc/looper/offering.go

Extend logging.

---

doc/ui/rpc.md
main.go
ui/auth_test.go
ui/channel.go
ui/export_test.go
ui/handler.go
ui/handler_test.go
ui/userrole.go
ui/userrole_test.go

Add getUserRole method to RPC API.

---

doc/ui/rpc.md
ui/channel.go
ui/channel_test.go

Replace status strings to status arrays in a getClientChannels method.

---

country/country.go
dappctrl-dev.config.json
dappctrl-test.config.json
dappctrl.config.json
doc/config.md
eth/backend.go
eth/client.go
eth/config.go
main.go
messages/ept/service.go
monitor/monitor.go
proc/looper/loop.go
scripts/configs_prettify.sh
somc/conn.go

Add script and `go:generate` to prettify config files and get keys ordered.
Convert all timeouts to milliseconds.
Remove unused configs and update documentation.
No new entries to config files were added.

Remove unused configs and update documentation + some refactoring.

---

ui/channel.go
ui/channel_test.go
ui/usage.go
ui/usage_test.go

documentation changed in the base branch #386

getChannelUsage returns detailed usage on channel

---

data/jobs.go
doc/ui/rpc.md
proc/worker/client.go
proc/worker/client_test.go
ui/channel.go
ui/channel_test.go

Add deposit argument to top up channel.

---

job/queue.go

Add job type to log message.

---

proc/worker/agent.go
proc/worker/agent_test.go

Update offering.blockNumberUpdated in AgentAfterOfferingMsgBCPublish job.

---

data/account_test.go
data/recover.go
data/recover_test.go
main.go

Recover service statuses for client channels

---

agent/bill/monitor_test.go
agent/somcsrv/handler_test.go
client/bill/monitor_test.go
dappctrl-test.config.json
data/recover_test.go
eth/util/util_test.go
job/queue_test.go
messages/crypto_test.go
messages/ept/service_test.go
monitor/monitor_test.go
pay/pay_test.go
proc/channel_test.go
proc/looper/loop_test.go
proc/worker/worker_test.go
sesssrv/server_test.go
ui/handler_test.go
util/log/test_logger.go
util/test.go

It can work in two modes: mute or verbose.
Resolves BV-1194.

Add test logger.

---

proc/worker/agent.go
proc/worker/agent_test.go

Run accountUpdateBalances job after complete agentAfterOfferingDelete job

---

proc/worker/agent.go
proc/worker/agent_test.go

Run accountUpdateBalances job after complete agentAfterOfferingMsgBCPublish job

---

proc/worker/client.go

Fix increase deposit logic.

---

dappctrl-dev.config.json
main.go
nat/errors.go
nat/nat.go
nat/pmp.go
nat/run.go
nat/upnp.go
util/misc.go

Added UPnP and NAT-PMP mechanisms for opening external ports on a router for somc and pay servers.

Add NAT traversal.

---

.travis.yml
README.md
go.mod
go.sum
monitor/producer_test.go
pay/pay_test.go
scripts/build.sh
scripts/test.sh
sess/subscribe_test.go

@furkhat please, check (and fix) the tests:
The test results:
https://travis-ci.org/Privatix/dappctrl

add travis

---

proc/worker/account.go
proc/worker/account_test.go
proc/worker/agent.go
proc/worker/agent_test.go
proc/worker/event.go
ui/account_test.go

agent validate client deposit on after channel create

---

proc/worker/client.go
tool/rating/config.json
tool/rating/deals/deals.go
tool/rating/in.json
tool/rating/main.go

creates fake deals closes and outputs acoounts (addresses and keys) to a file so they could be imported.

rating tool

---

scripts/cli/README.md
scripts/cli/dappctrl_rpc.py
scripts/cli/import_account_from_json.py

Import an account from a JSON Keystore file:
```bash
python import_account_from_json.py /opt/privatix/backup.json 
```

add import from json
