data/schema.sql
Added to table offerings:
1) Blockchain status, that respresents, if offering was deactivated/removed
2) Block number, that should be used to represent, when offering was last pushed up or to delete old offering sometime. Without it we don't know, how fresh it is.
=> Offerings table status and block number

data/schema.sql
1. Relation from `offering` to `users` table replaced by simple eth_address
2. Relation from `channel` to `users` table replaced by simple eth_address
3. New table `accounts` introduced to store local ethereum accounts data
4. Table `users` altered just to store address to public key relation
5. `offerings` and `endpoints` has new flag `is_local` that indicates whether object was authored locally or retrieved from external source.
4. minor comments fixes
=> Relations removed and more

data/schema.go, data/test.go, job/queue.go, job/queue_test.go, main.go, proc/channel.go, proc/channel_test.go, proc/processor.go, sesssrv/server_test.go, util/test.go
This change adds support for channel suspension, activation and termination (not including the corresponding job handlers).
Resolves **BV-232**.
=> Processor for top-level business-logic routines.

README.md, dappctrl-test.config.json, data/test_data.sql, proc/channel.go, sesssrv/client.go, svc/dappvpn/dappvpn.config.json, svc/dappvpn/main.go, svc/dappvpn/misc.go, svc/dappvpn/mon/monitor.go, svc/dappvpn/mon/monitor_test.go
**This change contains**:
1. OpenVPN adapter executable in `svc/dappvpn`.
2. OpenVPN monitor package with the corresponding tests.
**Usage**:
1. Make sure you have a properly configured `dappvpn.config.json` in a same directory as the `dappvpn` executable.
2. Run OpenVPN server with `dappvpn` passed as a session trigger:
```
auth-user-pass-verify /path/to/dappvpn via-file
client-connect /path/to/dappvpn
client-disconnect /path/to/dappvpn
script-security 3
management <ip> <port>
```
3. Run `dappvpn` in the background to monitor OpenVPN sessions.
**Resolves BV-230**.
=> OpenVPN adapter.

monitor/schedule.go
Fixes wrong sql query append sequence when `maxRetryKey` is greater then zero.
=> Fix bc monitor schedule function 

agent/bill/monitor.go, client/bill/monitor.go, data/schema.go, monitor/monitor_test.go, proc/channel.go, proc/channel_test.go, proc/processor/processor.go, proc/worker/worker.go
This PR add support to safely transition service status for Client. Before that only agent supported.
=> add client support to proc/channel

client/svcrun/runner.go, client/svcrun/runner_test.go, client/svcrun/test.go, dappctrl-test.config.json, dappctrl.config.json, dappctrl.prod.config.json, data/schema.go, data/schema.sql, data/test.go, main.go, proc/worker/client.go, proc/worker/client_test.go, proc/worker/worker.go, sesssrv/start.go, svc/dappvpn/dappvpn.config.json, svc/dappvpn/main.go, svc/dappvpn/mon/monitor.go, svc/dappvpn/mon/monitor_test.go
This change includes the following items:
1. Service runner type which allows to launch service adapters.
2. The corresponding mock and tests.
3. Dappvpn support for OpenVPN-client launching and monitoring.
4. ClientPreServiceTerminate/Suspend/Unsuspend jobs call runner.
5. Various minor imporvements and refactoring.
Resolves BV-338.
=> Service runner for the client controller mode.

main.go, svc/dappvpn/main.go, util/log.go
There's no portable way to guarantee for child processes to exit when parent process exits. So we need to handle a proper manual cleanup which will guarantee killing all the child processes.
Resolves BV-554.
=> Guarantee to close adapters after exiting controller.

data/log/logger.go, data/schema.go, data/schema.sql, util/errors/error.go, util/log/errors.go, util/log/file_logger.go, util/log/logger.go, util/log/multi_logger.go
This change introduces error codes to simplify error handling,
as well as context-aware logging to file and database.
This change includes the following definitions:
1. Error codes which implement standard error interface.
2. LoggerBase type for functionality shared between other loggers.
3. Functions for creating file and database loggers.
4. Function for combining existing loggers.
Resolves BV-544.
=> Enhanced error and logging support.

dappctrl-dev.config.json, dappctrl.config.json, eth/client.go, eth/config.go, main.go, monitor/monitor.go, monitor/monitor_test.go, proc/worker/worker.go, proc/worker/worker_test.go
Resolves BV-624.
- HTTP-based Ethereum client now based on a separate transport.
- Added functionality that closes the stuck sockets.
- Added more timeouts to http client.
=> Customization HTTP-based Ethereum client.

data/schema.go, proc/worker/agent.go, uisrv/channel.go, uisrv/channel_test.go, uisrv/db.go, uisrv/offering.go
* client now can trigger uncooperative close request.
* uisrv uses `proc` package for service status changes.
* agent jobs use `proc` package for service termination.
* removed not used `agentPreCooperativeClose`. Cooperative close happens at service termination.
=> uncoop close req triggering and some refactoring

dappctrl-dev.config.json, dappctrl.config.json, proc/worker/client.go, proc/worker/client_test.go
Client uncooperative close now requires service to be either in pending or terminated state.
=> client uncoop close tuning

job/queue.go, job/queue_test.go, job/test.go, ui/errors.go, ui/misc.go, ui/offering.go, ui/offering_test.go, ui/subscribe.go, ui/subscribe_test.go, util/test.go
This change includes:
1. Queue now supports multi-object subscriptions per single call.
2. Implementation for the new `objectChange` subscription type.
3. The `acceptOffering` method doesn't support subscriptions.
**Note**:
The changes correspond to the following UI API:
https://github.com/Privatix/dappctrl/wiki/JSON-RPC
https://github.com/Privatix/dappctrl/wiki/UI-JSON-RPC
=> Support subscriptions for object state changes.

svc/connector/connector.go, svc/connector/test.go
Resolves BV-689.
The method is required for the interaction of a client-specific openvpn adapter and a controller.
=> Add GetEndpointMessage method and mock to connector.

data/prod_data.sql, data/schema.go, sesssrv/client.go, sesssrv/session_test.go, sesssrv/start.go, svc/dappvpn/config/config.go, svc/dappvpn/data/offering.go, svc/dappvpn/main.go, tc/errors.go, tc/tc.go, tc/tc_darwin.go, tc/tc_linux.go, tc/tc_windows.go
This is an initial implementation of traffic control for the client VPN sessions. Currently only download rate is constrained and on Linux only.
This commit includes the following changes:
1. The start session call now returns an offering.
2. Added a new `tc` package for traffic control.
3. Dappvpn calls SetRateLimit/UnsetRateLimit.
Resolves BV-786.
=> Assign bandwidth limit on client VPN connections

data/command.go
This commit includes the following changes:
1.  `db-version` - command to display version of the database schema
2.  executing migration scripts to upgrade/downgrade database schema.
Resolves BV-858.
=> commands to downgrade the database schema and display version

country/country.go, country/errors.go, country/test.go, dappctrl-dev.config.json, dappctrl.config.json, data/migration/scripts/00001_schema_down.sql, data/migration/scripts/00001_schema_up.sql, data/schema.go, data/schema.sql, main.go, proc/worker/agent.go, proc/worker/agent_test.go, proc/worker/client.go, proc/worker/client_test.go, proc/worker/errors.go, proc/worker/misc.go, proc/worker/selectors.go, proc/worker/worker.go, proc/worker/worker_test.go, sesssrv/product.go, sesssrv/server.go, sesssrv/server_test.go, svc/dappvpn/msg/config_test.go, svc/dappvpn/msg/msg_test.go, svc/dappvpn/msg/parsing_test.go, svc/dappvpn/msg/pusher_test.go, svc/dappvpn/prepare/prepare_test.go
Changes:
* Move country detection functionality to a new package.
* Add the functional definition of a country for any ip address.
* Check offering country by IP address from endpoint message during ClientPreEndpointMsgSOMCGet job  execution.
* Fill `DB.Offering.Country` from `DB.Product.Country`.
* Fill `DB.Product.Country` during pushing product configuration.
Resolves BV-728.
=> Checking offering country by IP address from endpoint message.

data/test.go, proc/worker/agent.go, ui/errors.go, ui/offering.go, ui/offering_test.go, uisrv/offering.go, uisrv/offering_test.go
Agent can't create offering if there is one that has not been published yet. This is because of unique constraint we declare on `offering.hash` field and because we compute has in `AgentPreOfferingMsgBCPublish`. **Solution**: set offering hash at creation.
The other change related to offering update. Right now we don't have this use case, so I deleted related `uisrv` endpoint and `ui` method
=> set offering hash at creation to resolve unique contraint error

svc/dappvpn/prepare/errors.go, svc/dappvpn/prepare/prepare.go
If username is wrong in dappvpn.config.json, then will be errors in a log:
Agent:
* `dappctrl`: WARNING access denied map[sender:ip:port type:sesssrv.Server method:RequireBasicAuth]
Client:
* `dappctrl`: WARNING access denied map[type:sesssrv.Server method:RequireBasicAuth sender:ip:port]
* `dappvpn`: FATAL failed to prepare client configuration: server responed with error: access denied (3) map[channel:channel id]
Resolves BV-880.
=> Clearly register error in log about failed authentication.

proc/worker/agent.go, proc/worker/agent_test.go
If `channel.ReceiptBalance` = 0, then no need to call a `PSC.cooperativeClose()`.
Resolves BV-924.
=> Fix agentPreServiceTerminate.

.gitignore, client/svcrun/exec/proc_unix.go, client/svcrun/exec/proc_windows.go, client/svcrun/runner.go, client/svcrun/runner_test.go
This PR includes the following changes:
1. The package has been refactored to be platform-agnostic.
2. Added a new client/svcrun/exec package with platform-specific
implementation for Unix and Windows.
Partially resolves BV-921.
=> Make the client/svcrun package to support Windows.

dappctrl-dev.config.json, dappctrl.config.json, eth/backend.go, eth/client.go, eth/config.go, eth/test.go, main.go, monitor/monitor.go, monitor/monitor_test.go, proc/looper/loop_test.go, proc/looper/offering.go, proc/worker/client_test.go, proc/worker/worker.go, proc/worker/worker_test.go
Changes:
- Move Ethereum backend from `github.com/privatix/dappctrl/proc/adapter` to `github.com/privatix/dappctrl/eth`
- Ethereum backend exclusively owns a Ethereum connection.
- Reconnect mechanism to Ethereum.
Resolves BV-892.
=> Reconnect to Ethereum node after lost connection.

agent/bill/inactive_test.go, client/bill/monitor.go, client/bill/monitor_test.go, data/migration/scripts/00001_schema_up.sql, data/schema.go, data/test.go, messages/offer/types.go, proc/worker/agent_test.go, ui/channel.go, ui/channel_test.go, uisrv/channel.go, uisrv/channel_test.go, uisrv/offering_test.go, uisrv/server_test.go
=> Field `offering.max_inactive_time_sec` is not null.

data/prod_data.sql, data/settings.go, proc/worker/agent.go, proc/worker/agent_test.go, proc/worker/worker.go
Add tor setting to dynamically control what somc type to use.
`AgentPreOfferingMsgBCPublish` and `AgentPreOfferingPopUp` - based on setting decides what somc type to use on publish.
`AgentPreEndpointMsgCreate` and `AgentAfterOfferingMsgBCPublish` - based on related offering's somc type decides whether to publish endpoint or not.
=> add tor setting

data/create_db.sql
Closes all active connection before  execute `drop database`.
=> fix create_db.sql

doc/ui/rpc.md, ui/channel.go, ui/channel_test.go
=> Return "unitName" and "unitType" for getChannelUsage and getClientChannels UI RPC methods.

dappctrl-dev.config.json, dappctrl-test.config.json, dappctrl.config.json, data/prod_data.sql, doc/config.md, proc/worker/worker.go
- some gas limits were completely removed, as they apply to public smart-contract method, which doesn't require gas at all
- error reporting was disabled by default
- gas limit updated to be closer to real usage, while still having 10% to 30% margin
=> update gas limit, autopopup, error reporting

dappctrl-dev.config.json, dappctrl-test.config.json, dappctrl.config.json, doc/config.md
Android studio is often use `5555` port for Android Debug Bridge.
So, we should change it by default to `3452`
=> change 5555 port to 3452
